name: WaveWatch
description: A mobile app for collection of users experience data from mobile network subscribers.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_internet_speed_test:
    path: packages/flutter_internet_speed_test
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  connectivity_plus: ^5.0.2
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.3.0
  flutter_background_service_ios: ^5.0.0
  flutter_local_notifications: ^19.2.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  http: ^1.1.0
  intl: ^0.20.0
  fl_chart: ^1.0.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  flutter_rating_bar: ^4.0.1
  uuid: ^4.2.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  flutter_network_speed_test: ^0.1.5
  path: ^1.8.3
  network_info_plus: ^4.0.2
  device_info_plus: ^11.4.0
  camera: ^0.11.1
  telephony: ^0.2.0
  flutter_secure_storage: ^9.2.4
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
